# Generated by Django 3.1.4 on 2020-12-28 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0004_auto_20201221_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funcionario',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
    ]
